Repository for-Adhd-restore/chatbot-server-new, pull requests merged in 2025-09, with the labels that each got.

#17 Fix: db localhost에서 서비스명으로 변경
  src/main/resources/application.properties
Labels: :bug: fix, ⚙️ chore, 💚 은수

#18 Fix/12/db connection error
  docker-compose.yml
  src/main/resources/application.properties
Labels: :bug: fix, ⚙️ chore, 💚 은수

#43 [BUG] apple login issue solve
  .gitignore
  src/main/java/com/forA/chatbot/auth/service/AppleTokenValidator.java
Labels: :bug: fix, D-0

#48 [Feat] 복약 관련 API 개발 완료
  .github/workflows/mori-dev-cicd.yml
  src/main/java/com/forA/chatbot/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/forA/chatbot/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/forA/chatbot/medications/controller/MedicationController.java
  src/main/java/com/forA/chatbot/medications/domain/MedicationBundle.java
  src/main/java/com/forA/chatbot/medications/dto/MedicationUpdateRequestDto.java
  src/main/java/com/forA/chatbot/medications/dto/NotificationUpdateDto.java
  src/main/java/com/forA/chatbot/medications/dto/TodayMedicationResponseDto.java
  src/main/java/com/forA/chatbot/medications/repository/MedicationBundleRepository.java
  src/main/java/com/forA/chatbot/medications/repository/MedicationItemRepository.java
  src/main/java/com/forA/chatbot/medications/repository/MedicationLogRepository.java
  src/main/java/com/forA/chatbot/medications/service/MedicationService.java
Labels: :sparkles: feat, 💚 은수, D-1

#53 [Fix] key path 관련 주석 해제
  .gitignore
  src/main/resources/application.properties
  src/test/resources/application-test.properties
Labels: :bug: fix, 💚 은수, D-0

#47 [FEAT] 유저 관련 api 구현
  .gitignore
  build.gradle
  src/main/java/com/forA/chatbot/ChatbotApplication.java
  src/main/java/com/forA/chatbot/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/forA/chatbot/auth/controller/AuthController.java
  src/main/java/com/forA/chatbot/auth/domain/BlacklistedToken.java
  src/main/java/com/forA/chatbot/auth/dto/LogoutResponse.java
  src/main/java/com/forA/chatbot/auth/dto/RefreshTokenRequest.java
  src/main/java/com/forA/chatbot/auth/dto/RefreshTokenResponse.java
  src/main/java/com/forA/chatbot/auth/jwt/CustomUserDetails.java
  src/main/java/com/forA/chatbot/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/forA/chatbot/auth/jwt/JwtUtil.java
  src/main/java/com/forA/chatbot/auth/repository/BlacklistedTokenRepository.java
  src/main/java/com/forA/chatbot/auth/repository/UserRepository.java
  src/main/java/com/forA/chatbot/auth/service/AppleAuthService.java
  src/main/java/com/forA/chatbot/auth/service/AuthService.java
  src/main/java/com/forA/chatbot/auth/service/BlacklistService.java
  src/main/java/com/forA/chatbot/auth/service/TempAuthService.java
  src/main/java/com/forA/chatbot/chat/domain/ChatSession.java
  src/main/java/com/forA/chatbot/config/SwaggerConfig.java
  src/main/java/com/forA/chatbot/medications/domain/MedicationBundle.java
  src/main/java/com/forA/chatbot/medications/repository/MedicationBundleRepository.java
  src/main/java/com/forA/chatbot/medications/repository/MedicationLogRepository.java
  src/main/java/com/forA/chatbot/medications/service/MedicationService.java
  src/main/java/com/forA/chatbot/providers/Provider.java
  src/main/java/com/forA/chatbot/subscriptions/Subscription.java
  src/main/java/com/forA/chatbot/user/Disorder.java
  src/main/java/com/forA/chatbot/user/Job.java
  src/main/java/com/forA/chatbot/user/Symptom.java
  src/main/java/com/forA/chatbot/user/User.java
  src/main/java/com/forA/chatbot/user/controller/UserController.java
  src/main/java/com/forA/chatbot/user/converter/DisorderSetConverter.java
  src/main/java/com/forA/chatbot/user/converter/JobSetConverter.java
  src/main/java/com/forA/chatbot/user/converter/SymptomSetConverter.java
  src/main/java/com/forA/chatbot/user/domain/User.java
  src/main/java/com/forA/chatbot/user/domain/UserResponse.java
  src/main/java/com/forA/chatbot/user/domain/enums/DisorderType.java
  src/main/java/com/forA/chatbot/user/domain/enums/JobType.java
  src/main/java/com/forA/chatbot/user/domain/enums/SymptomType.java
  src/main/java/com/forA/chatbot/user/dto/NicknameRequest.java
  src/main/java/com/forA/chatbot/user/dto/NicknameResponse.java
  src/main/java/com/forA/chatbot/user/dto/UserDeleteResponse.java
  src/main/java/com/forA/chatbot/user/dto/UserProfileResponse.java
  src/main/java/com/forA/chatbot/user/dto/UserProfileUpdateRequest.java
  src/main/java/com/forA/chatbot/user/dto/UserResetResponse.java
  src/main/java/com/forA/chatbot/user/scheduler/UserDeletionScheduler.java
  src/main/java/com/forA/chatbot/user/service/UserService.java
  src/main/java/com/forA/chatbot/user/util/EnumConverterUtil.java
  src/main/resources/application.properties
Labels: :bug: fix, :sparkles: feat, ❤️ 주연, D-1
